
Server:
  zmq-io-threads: !Property
    type: int
    min: 1
    max: 65535
    default: 1
    description: >
      ZMQ IO threads to use. See zmq_init(3) for more information
    command-line: [-z, --zmq-io-threads]
  status-socket: !Property
    type: string
    default: tcp://127.0.0.1:9376
    description: >
      Zeromq REP-type socket, which will respond with status messages
  statuses: !Array
    element:
      interval: !Property
        type: int
        min: 1
      snapshots: !Property
        type: int
        min: 1
        default: 2
    default:
      - interval: 60
    description: >
      Intervals at which to do status snapshots. Please don't do too much,
      because for each of interval snapshots timerfd() descriptor is created,
      status structure is copied at each interval `snapshot` times. And for
      each of them, the snapshot data will be sent in response to status
      command.
  max-requests: !Property
    type: int
    min: 4
    max: 1073741824
    default: 4096
    command-line: [-m, --limit-requests]
    description: >
      Limits maximum of concurrent requests at any given time.  Don't make too
      much because it allocates static buffer with 2 words for each request
      (An you also need some memory for requests itself). When buffer is full
      all requests will be rejected with "service-unavailable" error (usually
      503 status code) without parsing request.
  listen: !Array
    element:
      host: !Property
        type: string
      port: !Property
        type: int
        min: 1
        max: 65536
        default: 80
      fd: !Property
        type: int
        min: 0
        default: -1
  default-host: !Property
    type: string

Globals: &settings
  logging:
    level: !Property
      type: int
      min: 0
      max: 7
      default: 6
      description: >
        Verbosity of error log
      command-line: --log-level
      command-line-incr: [-v, --verbose]
      command-line-decr: [-q, --quiet]
    warning-timeout: !Property
      type: int
      min: 0
      max: 3600
      default: 300
      description: >
        Timeout of displaying repeatable warnings
        Very small value will flood your logfile, but very
        big value will not make you confident when the
        problem is gone (wait at least this timeout
        and a minute or so on overloaded server, unless
        you know truth by some other means)
      command-line: [-w, --warning-timeout]
    access: !Property
      type: file
      default: "/var/applog/zerogw/access.log"
      check-existence: no
      check-dir: yes
      description: >
        Where to write access log messages. Use "-" for stderr.
      command-line: [-l, --access-log]
    error: !Property
      type: file
      default: "/var/applog/zerogw/error.log"
      check-existence: no
      check-dir: yes
      description: >
        Where to write error log messages. Use "-" for stderr.
      command-line: [-e, --error-log]
  contents: !Array
    element: !Property
      type: string
    default:
      - Cookie-SID
      - PostBody
  headers: !Mapping
    element: !Property
      type: string
  limits:
    method: !Array
      element: !Property
        type: string
      default:
        - POST
    max-body-size: !Property
      type: int
      min: 0
      default: 65536 # 64k
  responses:
    domain-not-found: &response
      code: &statuscode !Property
        type: int
        min: 100
        max: 999
        default: 404
      status: !Property
        type: string
        default: |-
          Not Found
      body: !Property
        type: string
        default: |
          <html>
            <head>
              <title>404 Not Found</title>
            </head>
            <body>
              <h1>404 Not Found</h1>
            </body>
          </html>
    uri-not-found: *response
    method-not-allowed:
      code: !Property
        type: int
        min: 100
        max: 999
        default: 405
      status: !Property
        type: string
        default: |-
          Method Not Allowed
      body: !Property
        type: string
        default: |
          <html>
            <head>
              <title>404 Method Not Allowed</title>
            </head>
            <body>
              <h1>404 Method Not Allowed</h1>
            </body>
          </html>
    internal-error:
      code: !Property
        <<: *statuscode
        default: 500
      status: !Property
        type: string
        default: |-
          Internal Server Error
      body: !Property
        type: string
        default: |
          <html>
            <head>
              <title>500 Internal Server Error</title>
            </head>
            <body>
              <h1>Internal Server Error</h1>
              Sorry, you can retry again later
            </body>
          </html>
    service-unavailable:
      code: !Property
        <<: *statuscode
        default: 503
      status: !Property
        type: string
        default: |-
          Service Unavailable
      body: !Property
        type: string
        default: |
          <html>
            <head>
              <title>503 Service Unavailable</title>
            </head>
            <body>
              <h1>Service Unavailable</h1>
              Probably too many users currently connected or some DoS attack on
              our servers is going on. Please try again later.
            </body>
          </html>
Pages: !Mapping
  element:
    <<: *settings
    pages: !Array
      element:
        <<: *settings
        uri: !Property
          type: string
        static-string: !Property
          type: string
        forward: !Array
          element: !Property
            type: string
